import React, {Component} from 'react';
import PropTypes from 'prop-types';
import Typography from '@material-ui/core/Typography';
import {withStyles} from '@material-ui/core/styles';
import theme from "../styles/Styles";
import MuiExpansionPanel from '@material-ui/core/ExpansionPanel';
import MuiExpansionPanelSummary from '@material-ui/core/ExpansionPanelSummary';
import MuiExpansionPanelDetails from '@material-ui/core/ExpansionPanelDetails';
import ReactMarkdown from "react-markdown";
import ExpandMoreIcon from '@material-ui/icons/ExpandMore';


const ExpansionPanel = withStyles({
    root: {
        border: '1px solid rgba(0,0,0,.125)',
        boxShadow: 'none',
        '&:not(:last-child)': {
            borderBottom: 0,
        },
        '&:before': {
            display: 'none',
        },
    },
    expanded: {
        margin: 'auto',
    },
})(MuiExpansionPanel);

const ExpansionPanelSummary = withStyles({
    root: {
        backgroundColor: 'rgba(0,0,0,.03)',
        borderBottom: '1px solid rgba(0,0,0,.125)',
        marginBottom: -1,
        minHeight: 56,
        '&$expanded': {
            minHeight: 56,
        },
    },
    content: {
        '&$expanded': {
            margin: '12px 0',
        },
    },
    expanded: {},
})(props => <MuiExpansionPanelSummary {...props} />);

ExpansionPanelSummary.muiName = 'ExpansionPanelSummary';

const ExpansionPanelDetails = withStyles(theme => ({
    root: {
        padding: theme.spacing.unit * 2,
    },
}))(MuiExpansionPanelDetails);






class Library extends Component {
    state = {
        labelWidth: 0,
        loading: false,
        expanded: 'panel1',

    };


    handleChange = panel => (event, expanded) => {
        this.setState({
            expanded: expanded ? panel : false,
        });
    };

    render() {
        const {classes} = this.props;
        const { expanded } = this.state;


        return (

            <main className={classes.layout}>
                {/* Hero unit */}
                <div className={classes.heroContent}>
                    <Typography component="h1" variant="h2" align="center" color="primary"
                                className={classes.headingPadding}>
                        BİLGİ BANKASI
                    </Typography>

                </div>
                <div>
                    <ExpansionPanel expanded={expanded === 'panel1'} onChange={this.handleChange('panel1')}>
                        <ExpansionPanelSummary expandIcon={<ExpandMoreIcon/>}>
                            <Typography variant="h6" color="primary">Changelog</Typography>
                        </ExpansionPanelSummary>
                        <ExpansionPanelDetails>
                            <Typography>
                                <ReactMarkdown source={'### Changelog\n' +
                                '\n' +
                                'All notable changes to this project will be documented in this file. Dates are displayed in UTC.\n' +
                                '\n' +
                                'Generated by [`auto-changelog`](https://github.com/CookPete/auto-changelog).\n' +
                                '\n' +
                                '#### [v0.2.6](https://github.com/repentant/cwteam/compare/v0.2.5...v0.2.6)\n' +
                                '\n' +
                                '> 13 March 2019\n' +
                                '\n' +
                                '- excel download implemented [`093fdda`](https://github.com/repentant/cwteam/commit/093fddae71d81619d9dbcbf2ecb7a2684941fb82)\n' +
                                '- markdown installed [`92c385e`](https://github.com/repentant/cwteam/commit/92c385e28cbdf23cca5bfff0d91eef6446eced6d)\n' +
                                '- z-report cron added [`e4a8004`](https://github.com/repentant/cwteam/commit/e4a8004910dbaf4a39c93492017c6a33c330a8cc)\n' +
                                '\n' +
                                '#### v0.2.5\n' +
                                '\n' +
                                '> 5 March 2019\n' +
                                '\n' +
                                '- init [`3e27c43`](https://github.com/repentant/cwteam/commit/3e27c434ed3d260f455cd8228b6c556fb5fccd59)\n' +
                                '- deleted node modules [`22f17a3`](https://github.com/repentant/cwteam/commit/22f17a3c207ff4916b61020036f270f70a1c1fb9)\n' +
                                '- chip input added and custom chip implemented [`fab4e36`](https://github.com/repentant/cwteam/commit/fab4e36e34fa304cdd553f2d3de778fe7304f5c3) '}/>
                            </Typography>
                        </ExpansionPanelDetails>
                    </ExpansionPanel>
                    <ExpansionPanel expanded={expanded === 'panel2'} onChange={this.handleChange('panel2')}>
                        <ExpansionPanelSummary expandIcon={<ExpandMoreIcon/>}>
                            <Typography variant="h6" color="primary">Proje planlama ipuçları</Typography>
                        </ExpansionPanelSummary>
                        <ExpansionPanelDetails>
                            <Typography>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse malesuada lacus
                                ex, sit amet blandit leo lobortis eget. Lorem ipsum dolor sit amet, consectetur
                                adipiscing elit. Suspendisse malesuada lacus ex, sit amet blandit leo lobortis eget.
                            </Typography>
                        </ExpansionPanelDetails>
                    </ExpansionPanel>
                    <ExpansionPanel expanded={expanded === 'panel3'} onChange={this.handleChange('panel3')}>
                        <ExpansionPanelSummary expandIcon={<ExpandMoreIcon/>}>
                            <Typography variant="h6" color="primary">Temel SEO çalışmaları</Typography>
                        </ExpansionPanelSummary>
                        <ExpansionPanelDetails>
                            <Typography>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse malesuada lacus
                                ex, sit amet blandit leo lobortis eget. Lorem ipsum dolor sit amet, consectetur
                                adipiscing elit. Suspendisse malesuada lacus ex, sit amet blandit leo lobortis eget.
                            </Typography>
                        </ExpansionPanelDetails>
                    </ExpansionPanel>
                </div>


            </main>

        )
    }
}

Library.propTypes = {
    classes: PropTypes.object.isRequired,
};

export default withStyles(theme)(Library);
